// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbs0Hra8RFqq0jhmtucOHTctMMiE_zA_Q',
    appId: '1:185240568584:web:d6fb076b421b82201822bd',
    messagingSenderId: '185240568584',
    projectId: 'paily-app',
    authDomain: 'paily-app.firebaseapp.com',
    storageBucket: 'paily-app.firebasestorage.app',
    measurementId: 'G-PXRMTK2G5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyojgnvmWnUIDi-64psp7MV0T_Dt44bAk',
    appId: '1:185240568584:android:28e0a1b814f868da1822bd',
    messagingSenderId: '185240568584',
    projectId: 'paily-app',
    storageBucket: 'paily-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_j2pbBXe1-DiGsr3wQjWd9Y6M4lzf0QA',
    appId: '1:185240568584:ios:91cb4a104c5d470e1822bd',
    messagingSenderId: '185240568584',
    projectId: 'paily-app',
    storageBucket: 'paily-app.firebasestorage.app',
    iosBundleId: 'com.paily.paily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_j2pbBXe1-DiGsr3wQjWd9Y6M4lzf0QA',
    appId: '1:185240568584:ios:91cb4a104c5d470e1822bd',
    messagingSenderId: '185240568584',
    projectId: 'paily-app',
    storageBucket: 'paily-app.firebasestorage.app',
    iosBundleId: 'com.paily.paily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbs0Hra8RFqq0jhmtucOHTctMMiE_zA_Q',
    appId: '1:185240568584:web:a867a3fd55a6ae5f1822bd',
    messagingSenderId: '185240568584',
    projectId: 'paily-app',
    authDomain: 'paily-app.firebaseapp.com',
    storageBucket: 'paily-app.firebasestorage.app',
    measurementId: 'G-VDCN84ZKZV',
  );

}